### Find by id
GET http://localhost:8090/api/songs/42f6a46a-4da7-49c8-ba5f-33b9a69fc048

### Find all
GET http://localhost:8090/api/songs

### Create
POST http://localhost:8090/api/songs
Content-Type: application/json

{
  "author": "value",
  "title": "value",
  "lyrics": "value"
}

### Update
PUT http://localhost:8090/api/songs/42f6a46a-4da7-49c8-ba5f-33b9a69fc048
Content-Type: application/json

{
  "author": "new value",
  "title": "new value",
  "lyrics": "new value"
}
